sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t parth149/react-docker-app -f Dockerfile.dev .

script:
  - docker run parth149/react-docker-app npm run test -- --coverage

