sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t parth149/react-docker-app -f Dockerfile.dev .

script:
  - docker run -e CI=true parth149/react-docker-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-695220428629"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

